# Generated by Django 5.0.3 on 2024-03-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
