# Generated by Django 5.0.3 on 2024-03-17 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chat_code_chatuser_code_comment_code_like_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='code',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='like',
            name='code',
        ),
        migrations.RemoveField(
            model_name='message',
            name='code',
        ),
        migrations.RemoveField(
            model_name='post',
            name='code',
        ),
        migrations.RemoveField(
            model_name='postfiles',
            name='code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.RemoveField(
            model_name='userreletion',
            name='code',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChatUser',
        ),
    ]
