# Generated by Django 5.0.3 on 2024-03-17 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_chat_code_remove_comment_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
        migrations.AddField(
            model_name='chat',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='postfiles',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userreletion',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
