# Generated by Django 5.0.3 on 2024-03-17 11:13

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_chat_users_chat_code_comment_code_like_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='code',
            field=models.CharField(default=main.models.generate_unique_code, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='code',
            field=models.CharField(default=main.models.generate_unique_code, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='code',
            field=models.CharField(default=main.models.generate_unique_code, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='code',
            field=models.CharField(default=main.models.generate_unique_code, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='code',
            field=models.CharField(default=main.models.generate_unique_code, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.CharField(default=main.models.generate_unique_code, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='postfiles',
            name='code',
            field=models.CharField(default=main.models.generate_unique_code, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default=main.models.generate_unique_code, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userreletion',
            name='code',
            field=models.CharField(default=main.models.generate_unique_code, max_length=30, unique=True),
        ),
    ]
